#!/bin/bash
# vault_index.sh - regenerate vault_file_tree.md from a live find pass.
# Fires nightly at 23:30 (com.mbs.vault-index) and at login/boot (RunAtLoad).
# Idempotent: a per-day stamp prevents double-runs on the same calendar date.
# Does NOT require Obsidian to be running. Writes via the filesystem only.
#
# Output: VAULT/vault_file_tree.md - overwritten each run with a fresh listing.
# Excludes: trash/, _archive/, .obsidian/, attachments/, _to_clean/, create/oslo/_corpora/, health/health_physical/oura/raw/
# The listing is a sorted flat list of vault-relative paths (not a visual tree).
# Agents load this for existence checks (admin/mbs_system/brain/index.md retired 2026-07-28).

set -uo pipefail

VAULT="${VAULT:-/Users/cpreston/Vaults/storage_mbs}"
STATE_DIR="${STATE_DIR:-$HOME/.mbs_automation}"
STAMP="$STATE_DIR/last_vault_index_run"
LOG="$STATE_DIR/vault_index.log"
OUTPUT="$VAULT/admin/mbs_system/brain/vault_file_tree.md"

mkdir -p "$STATE_DIR"

# Sourced for alert_tasks_note() only, so a refusal below is visible in the
# vault and not just in this job's log. Same reason mbs_heartbeat.sh sources it.
# shellcheck source=./lib_auth.sh
source "$(dirname "$0")/lib_auth.sh"

# Always use Eastern time - P's timezone.
TODAY="$(TZ=America/New_York date +%Y-%m-%d)"
ts() { TZ=America/New_York date '+%Y-%m-%d %H:%M:%S'; }

# Already ran today? Stop.
if [ -f "$STAMP" ] && [ "$(cat "$STAMP" 2>/dev/null)" = "$TODAY" ]; then
  echo "$(ts) - already ran for $TODAY, skipping." >> "$LOG"
  exit 0
fi

echo "$(ts) - starting vault index run" >> "$LOG"

if [ ! -d "$VAULT" ]; then
  echo "$(ts) - ERROR: vault not found at $VAULT" >> "$LOG"
  exit 1
fi

# Collect all .md files, excluding opaque/noisy directories.
TREE="$(find "$VAULT" -name "*.md" \
  ! -path "*/trash/*" \
  ! -path "*/_archive/*" \
  ! -path "*/.obsidian/*" \
  ! -path "*/attachments/*" \
  ! -path "*/_to_clean/*" \
  ! -path "*/create/oslo/_corpora/*" \
  ! -path "*/health/health_physical/oura/raw/*" \
  | sort)"

COUNT="$(echo "$TREE" | grep -c . || true)"

# Strip vault prefix so paths are vault-relative (e.g. admin/mbs_system/homelab/homelab.md)
TREE_DISPLAY="$(echo "$TREE" | sed "s|$VAULT/||")"

# Plausibility guard before the tree is overwritten (added 2026-08-19).
#
# WHY: this script used to overwrite $OUTPUT and stamp success unconditionally.
# If find ever returned little or nothing (a permissions change, a moved or
# unmounted vault, a full disk mid-write), it would replace a 3,000-line tree
# with a hollow one and record the run as healthy. The damage is not the
# missing file, it is what the file then says: vault_file_tree.md is item 5 of
# the session-start read order in brain/CLAUDE.md, and the rule there is to
# grep it for existence checks. A hollowed-out tree makes every session
# confidently tell P that his files do not exist. Silent wrongness, which does
# more harm than silent absence.
#
# Same principle as web_watchers.sh refusing to store a CLI failure message as
# a watcher answer: a failed run must never be allowed to destroy a good
# baseline. Refuse, leave the old tree intact, do NOT stamp, let the next
# trigger retry, and say so where P will see it.
#
# Two tests: an absolute floor, and a halving guard against the previous run's
# own recorded count. If the vault ever legitimately shrinks by more than half
# (a mass archive), this refuses once and keeps refusing; the escape hatch is
# to delete vault_file_tree.md, which drops VI_PREV to 0 and leaves only the
# floor. That is deliberate: a 50% drop should need a human to confirm it.
VI_FLOOR=500
VI_PREV=0
if [ -f "$OUTPUT" ]; then
  VI_PREV="$(sed -n 's/^\*\*Last run:\*\* .* - \*\*\([0-9][0-9]*\) files\*\* indexed\..*/\1/p' "$OUTPUT" | head -1)"
  case "$VI_PREV" in
    ''|*[!0-9]*) VI_PREV=0 ;;
  esac
fi
VI_REFUSE=0
[ "$COUNT" -lt "$VI_FLOOR" ] && VI_REFUSE=1
if [ "$VI_PREV" -gt 0 ] && [ "$COUNT" -lt "$((VI_PREV / 2))" ]; then VI_REFUSE=1; fi
if [ "$VI_REFUSE" -eq 1 ]; then
  echo "$(ts) - REFUSING to overwrite $OUTPUT: this run found $COUNT markdown file(s) (absolute floor $VI_FLOOR, previous run $VI_PREV). The existing tree is left intact and NO stamp is written, so the next trigger retries. Check the vault path, the mount, and permissions. If the vault really did shrink this much, delete $OUTPUT to reset the baseline." >> "$LOG"
  alert_tasks_note "vault-index refused to rewrite vault_file_tree.md: this run found only $COUNT markdown file(s) against $VI_PREV last time, so it kept the old tree rather than replacing it with a hollow one. The tree is intact but going stale, and sessions grep it to decide whether a file exists. Check ~/.mbs_automation/vault_index.log."
  exit 1
fi

cat > "$OUTPUT" <<EOF
---
type: ref
date: ${TODAY}
auto_generated: true
tags: [admin, mbs_system]
---

# Vault file tree

Auto-generated by \`vault_index.sh\` (launchd \`com.mbs.vault-index\`). Regenerated nightly at 23:30 ET and at each login.

**Last run:** ${TODAY} - **${COUNT} files** indexed.

Excludes \`trash/\`, \`_archive/\`, \`.obsidian/\`, \`attachments/\`, \`_to_clean/\`, \`create/oslo/_corpora/\`, \`health/health_physical/oura/raw/\`.

Agents: load this file when you need to know whether a file exists before asking P. If a path is not listed here, verify with Glob before concluding it doesn't exist (this tree was generated at midnight; files created since then won't appear until the next run).

\`\`\`
${TREE_DISPLAY}
\`\`\`
EOF

echo "$TODAY" > "$STAMP"
echo "$(ts) - wrote ${COUNT} files to $OUTPUT" >> "$LOG"
exit 0
