#!/bin/bash
# vault_index.sh — regenerate vault_file_tree.md from a live find pass.
# Fires nightly at 23:30 (com.mbs.vault-index) and at login/boot (RunAtLoad).
# Idempotent: a per-day stamp prevents double-runs on the same calendar date.
# Does NOT require Obsidian to be running. Writes via the filesystem only.
#
# Output: VAULT/vault_file_tree.md — overwritten each run with a fresh listing.
# Excludes: trash/, _archive/, .obsidian/, attachments/, _to_clean/
# The listing is a sorted flat list of vault-relative paths (not a visual tree).
# Agents load this for existence checks (admin/mbs_system/brain/index.md retired 2026-07-28).

set -uo pipefail

VAULT="/Users/cpreston/Vaults/storage_mbs"
STATE_DIR="$HOME/.mbs_automation"
STAMP="$STATE_DIR/last_vault_index_run"
LOG="$STATE_DIR/vault_index.log"
OUTPUT="$VAULT/admin/mbs_system/brain/vault_file_tree.md"

mkdir -p "$STATE_DIR"

# Always use Eastern time — P's timezone.
TODAY="$(TZ=America/New_York date +%Y-%m-%d)"
ts() { TZ=America/New_York date '+%Y-%m-%d %H:%M:%S'; }

# Already ran today? Stop.
if [ -f "$STAMP" ] && [ "$(cat "$STAMP" 2>/dev/null)" = "$TODAY" ]; then
  echo "$(ts) — already ran for $TODAY, skipping." >> "$LOG"
  exit 0
fi

echo "$(ts) — starting vault index run" >> "$LOG"

if [ ! -d "$VAULT" ]; then
  echo "$(ts) — ERROR: vault not found at $VAULT" >> "$LOG"
  exit 1
fi

# Collect all .md files, excluding opaque/noisy directories.
TREE="$(find "$VAULT" -name "*.md" \
  ! -path "*/trash/*" \
  ! -path "*/_archive/*" \
  ! -path "*/.obsidian/*" \
  ! -path "*/attachments/*" \
  ! -path "*/_to_clean/*" \
  | sort)"

COUNT="$(echo "$TREE" | grep -c . || true)"

# Strip vault prefix so paths are vault-relative (e.g. admin/mbs_system/homelab/homelab.md)
TREE_DISPLAY="$(echo "$TREE" | sed "s|$VAULT/||")"

cat > "$OUTPUT" <<EOF
---
type: ref
date: ${TODAY}
auto_generated: true
tags: [admin, mbs_system]
---

# Vault file tree

Auto-generated by \`vault_index.sh\` (launchd \`com.mbs.vault-index\`). Regenerated nightly at 23:30 ET and at each login.

**Last run:** ${TODAY} — **${COUNT} files** indexed.

Excludes \`trash/\`, \`_archive/\`, \`.obsidian/\`, \`attachments/\`, \`_to_clean/\`.

Agents: load this file when you need to know whether a file exists before asking P. If a path is not listed here, verify with Glob before concluding it doesn't exist (this tree was generated at midnight; files created since then won't appear until the next run).

\`\`\`
${TREE_DISPLAY}
\`\`\`
EOF

echo "$TODAY" > "$STAMP"
echo "$(ts) — wrote ${COUNT} files to $OUTPUT" >> "$LOG"
exit 0
